server:
  port: 8008
dubbo:
  application:
    name: nacos-provider
        #用于运维的监控服务， 默认是开启状态，并且端口是22222。开发环境为了避免端口冲突，建议直接关掉
    qos-enable: false
    qos-accept-foreign-ip: false
     # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: 8998
  scan:
    base-packages: com.ads.nacos.provider.impl
  registry:
    id: nacos-provider
    address: nacos://127.0.0.1:8848?namespace=42e2b200-fbef-4b2c-bfad-f70fc4094f68

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      username: nacos
      password: nacos
#      sentinel:
#        eager: true
#        transport:
#          dashboard: 127.0.0.1:8080
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
        namespace: 42e2b200-fbef-4b2c-bfad-f70fc4094f68
        group: PROVIDER_GROUP
  datasource:
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 610547
    show-sql: true
    ###################连接池的补充设置，应用到上面所有数据源中  ###########################
    type: com.alibaba.druid.pool.DruidDataSource
        # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
        # 配置获取连接等待超时的时间
    maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # mysql的话是select ‘x’ oracle则是select ‘x’ FROM DUAL postgresql是select version();
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
   
#Spring Boot 应用支持通过 Endpoint 来暴露相关信息，需要在 maven 中添加 spring-boot-starter-actuator依赖
management:
  endpoints:
    web:
      exposure:
        include: "*"   
    
mybatis-plus: 
#  mapper-locations: classpath*:/mybatis/*.xml
  type-aliases-package: com.ads.nacos.api.model
  configuration:
        #是否开启自动驼峰命名规则
    map-underscore-to-camel-case: true
        #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: false
        
logging: 
  config: classpath:logback-spring.xml
  file:
    path: logs/