server:
  port: 8011

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848 # 配置Nacos地址
        namespace: 42e2b200-fbef-4b2c-bfad-f70fc4094f68
        group: NACOS_GROUP
    gateway:
      discovery:
        locator:
                      # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
                      # 服务名小写
          lower-case-service-id: true
      routes:
        # http://localhost:8011/guonei
      - id: forward-route
        # uri:目标服务地址 uri: http://www.baidu.com
        # lb代表从注册中心获取服务，且已负载均衡方式转发 uri: lb://nacos-provider
        uri: http://news.baidu.com/guonei
        # predicates(断言):路由条件,Predicate 接受一个输入参数,返回一个布尔值结果
        predicates:
        - Path=/guonei
        
        # http://localhost:8011/api-consumer/info
        # http://localhost:8011/api-consumer/info?token=???开启tokenFilter用这个
      - id: consumer-route
        uri: lb://nacos-consumer
        predicates:
        - Path=/api-consumer/**
        filters:
        # StripPrefix:路径剥离，剥离个数1个 --->localhost:8011/api-consumer/info --->  localhost:8010/info
        - StripPrefix=1
        
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always